### ISSUE TITLE
Support ddesrosiers/silex-annotation-provider 3.x

### ISSUE THREAD

**Issue by bperel** [DerManoMann/silex2swagger#19]
`ddesrosiers/silex-annotation-provider` 3.0 was [released in December](https://github.com/danadesrosiers/silex-annotation-provider/releases/tag/v3.0.0). Would it be feasible to make silex2swagger compatible with this new version?

**Comment by DerManoMann** [comment]
Would be tricky to make both work at the same time.
However, I have started a new project for this :) that is in the early stages and was intended more to force me to play with different frameworks (Laravel, Slim, Lumen).
I should be able to add Silex again, althought I cannot give you a timeframe at all...

**Comment by DerManoMann** [comment]
Realized I never mentioned the repo....

https://github.com/DerManoMann/openapi-router

It uses a dfferent approach though, in that it just uses swagger-php annotations + some custom options per framework adapter to convert them to framework routes.
