### ISSUE TITLE
@SWG\Parameter and @SWG\Response annotations are not inherited from controller class

### ISSUE THREAD

**Issue by bperel** [DerManoMann/silex2swagger#9]
I wish to require a header parameter to be included in all the routes of a controller. Intuitively I tried:

```php
/**
 * @SLX\Controller(prefix="/")
 * @SLX\Route(
 *   @SWG\Parameter(
 *     name="x-api-version",
 *     in="header",
 *     required=true
 *   )
 * )
 */
class AppController
{
    /**
     * @SLX\Route(
     *   @SLX\Request(method="GET", uri="list/countries"),
     *
     *   @SWG\Response(response=200),
     *   @SWG\Response(response="default", description="Error")
     * )
     * @param Application $app
     * @param Request $request
     * @return JsonResponse
     */
    public function listCountries(Application $app, Request $request) {
        ...
    }
```

This triggers the following error when running `silex2swagger:build`:
```
PHP Warning:  Invalid argument supplied for foreach() in ...\vendor\ddesrosiers\silex-annotation-provider\src\Annotations\Route.php on line 72
```

The README specifies that:

> In order to accurately merge/group annotations it is necessary to use the @SLX\Route

so I thought that my case covered this. If I put the `@SWG\Parameter` block in the method's annotation no error is triggered.

**Comment by DerManoMann** [comment]
Nice idea - since the Controller annotation is a Silex annotation I wonder if this is even supported in swagger-php. I guess it would be possible, tho...

**Comment by DerManoMann** [comment]
I've pushed some changes into a branch controller_shared_parameter - could you try that to see if it does what you want?

**Comment by bperel** [comment]
Having a look at the example in the README it looks like it's what I want, but the output contains issues.

Controller:

```php
/**
 * @SLX\Controller(prefix="/",
 *   @SWG\Parameter(
 *     name="x-dm-version",
 *     in="header",
 *     required=true
 *   )
 * )
 *
 */
class AppController extends AbstractController
{
    /**
     * @SLX\Route(
     *   @SLX\Request(method="GET", uri="list/countries"),
     *
     *   @SWG\Response(response=200),
     *   @SWG\Response(response="default", description="Error")
     * )
     * @param Application $app
     * @param Request $request
     * @return JsonResponse
     */
    public function listCountries(Application $app, Request $request) {
        ...
```

Output: 
```json
{
    ...
    "paths": {
        "\/{\n    \"name\": \"x-api-version\",\n    \"in\": \"header\",\n    \"required\": true\n}\/list\/countries": {
            "get": {
                "operationId": "listCountries",
                "parameters": [
                    {
                        "parameter": "\n    \"name\": \"x-api-version\",\n    \"in\": \"header\",\n    \"required\": true\n",
                        "name": "\n    \"name\": \"x-api-version\",\n    \"in\": \"header\",\n    \"required\": true\n",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {},
                    "default": {
                        "description": "Error"
                    }
                }
            }
        }
    },
    "definitions": {},
    "parameters": {
        "x-api-version": {
            "name": "x-api-version",
            "in": "header",
            "required": true
        },
        "countries": {
            "name": "countries",
            "in": "path",
            "required": true
        }
    },
    "responses": {
        "200": {},
        "default": {
            "description": "Error"
        }
    }
}
```

Any reason why it would do this ?

**Comment by DerManoMann** [comment]
Not really - would you be able to provide the annotations of that class for me to test?

**Comment by bperel** [comment]
Sure, I updated my comment with the controller's annotations

**Comment by DerManoMann** [comment]
Cool. I think I can see the issue - there is a subtle difference in the example:
````
 * @S2S\Controller(
````
I had to introduce a custom Controller annotation as we need a property on the annotation to store the nested Parameters. So, updating the namespace for the Controller annotation should fix this.

**Comment by bperel** [comment]
My bad, you're right! Works for me now :-)

**Comment by bperel** [comment]
Now I'm thinking that it could be a good idea to allow to inherit `@SWG\Response` as well, since quite often the error response handling is similar among a controller's requests... What do you think ?

**Comment by DerManoMann** [comment]
Well its not much more work - in fact that is one things that annoys me too :) Let's see...

**Comment by DerManoMann** [comment]
Haha, not much more work, except that I had to dig much deeper into doctrine annotations to make things work - long live a propert debugger!

Could you try again and if that is cool I'll merge to master and cut a new release

**Comment by bperel** [comment]
It looks like you had fun digging into Doctrine's code ^^
The `@SWG\Response` inheritance seems to work except when the method itself doesn't contain `@SWG\Response` annotations: in that case I get:

`Warning: array_merge(): Argument #1 is not an array in ...\silex2swagger\src\Swagger\S2SConverter.php on line 272`.

I guess that `$swgOperation->responses` variable is `NULL `if no such annotation is declared on the method's scope, which triggers the error.

Replacing line 272 of S2SConverter by : 
`$swgOperation->responses = array_merge(is_null($swgOperation->responses) ? [] : $swgOperation->responses, $controller->responses);`
fixes it, but it may not be the best way to do it and maybe I'm missing other edge cases

**Comment by DerManoMann** [comment]
Good testing :) Extended code to deal with single nexted annotation (which does not come in an array...)
Hopefully this should be good to go now.

**Comment by bperel** [comment]
I'm afraid I still get the same error: `$swgOperation->responses` variable is `NULL` if there is no `@SWG\Response` annotation corresponding to the method. It all works well if the method has at least one `@SWG\Response` annotation.

**Comment by DerManoMann** [comment]
hmm

**Comment by bperel** [comment]
@DerManoMann Do you not get the same error as me?

**Comment by DerManoMann** [comment]
Sorry, had a few busy days. I finally managed to get this replicated - the tests all had explicit responses too and that masked the problem. One more try? ;)

**Comment by bperel** [comment]
Works well now :-)
